server:
  port: 8085

spring:
  application:
    name: sales-service

  datasource:
    url: jdbc:mysql://localhost:3306/sales_service?serverTimezone=UTC
    username: root
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

